# Generated by Django 3.1.5 on 2021-08-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20210722_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonename', models.CharField(max_length=20, unique=True)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.floormap')),
            ],
        ),
    ]
