# Generated by Django 3.1.5 on 2021-08-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210805_1151'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeregistration')),
                ('zoneid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zones')),
            ],
        ),
    ]
