# Generated by Django 3.1.5 on 2021-08-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_monthlyzonetracking_weeklyzonetracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyzonetracking',
            old_name='tagid',
            new_name='count',
        ),
    ]
