# Generated by Django 3.1.5 on 2021-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irq',
            name='battery',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturehumidity',
            name='battery',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
