# Generated by Django 3.1.5 on 2021-08-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210722_1249'),
        ('sensor', '0004_auto_20210810_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IRQ',
            new_name='IAQ',
        ),
        migrations.CreateModel(
            name='WeeklyIAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('tvoc', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.iaq')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('tvoc', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.iaq')),
            ],
        ),
        migrations.CreateModel(
            name='DailyIAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('tvoc', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.iaq')),
            ],
        ),
    ]
