# Generated by Django 3.1.5 on 2021-07-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(max_length=20, unique=True)),
                ('battery', models.FloatField()),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('phoneno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('tagid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeetag')),
            ],
        ),
    ]
