# Generated by Django 3.1.5 on 2021-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='intime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
