# Generated by Django 3.1.5 on 2021-07-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210722_1249'),
        ('employee', '0002_employeeregistration_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetag',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.floormap'),
        ),
    ]
