# Generated by Django 3.1.5 on 2021-07-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_distancecalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancecalculation',
            name='empid',
            field=models.CharField(max_length=100),
        ),
    ]
