# Generated by Django 3.1.5 on 2021-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210729_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='intime',
            field=models.DateTimeField(),
        ),
    ]
