# Generated by Django 3.1.5 on 2021-07-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20210722_1249'),
        ('common', '0002_auto_20210407_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='FloorMap',
        ),
    ]
