# Generated by Django 3.1.5 on 2021-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRepeator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macid', models.CharField(max_length=20, unique=True)),
                ('lastseen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
